Repository Central-MakeUs/suppin-web, pull requests merged in 2024-07, with the labels that each got.

#2 chore: [2] 웹뷰 초기 세팅
  .github/workflows/pr-check.yml
  web/.editorconfig
  web/.eslintignore
  web/.eslintrc.cjs
  web/.gitignore
  web/.gitkeep
  web/.nvmrc
  web/.prettierignore
  web/.prettierrc
  web/README.md
  web/index.html
  web/package-lock.json
  web/package.json
  web/public/logo.svg
  web/src/App.tsx
  web/src/main.tsx
  web/src/pages/home-page.tsx
  web/src/pages/index.ts
  web/src/styles/global-styles.ts
  web/src/vite-env.d.ts
  web/tsconfig.app.json
  web/tsconfig.json
  web/tsconfig.node.json
  web/vite.config.ts
Labels: chore

#4 feat: [4] 로그인 화면, splashscreen 디자인 구현 및 ip 설정
  .DS_Store
  web/package-lock.json
  web/package.json
  web/src/assets/icons.tsx
  web/src/pages/home-page.tsx
  web/src/store/useLoginStore.ts
  web/src/theme.ts
  web/src/types/HomePage.d.ts
  web/vite.config.ts
Labels: feat

#6 chore: [5] 앱 기본 초기 세팅
  app/.gitignore
  app/README.md
  app/app.json
  app/app/_layout.tsx
  app/assets/.gitkeep
  app/babel.config.js
  app/components/.gitkeep
  app/package-lock.json
  app/package.json
  app/tsconfig.json
Labels: chore

#10 feat: [8] vitest를 이용한 test 초기 설정
  .github/workflows/pr-test.yml
  web/package-lock.json
  web/package.json
  web/tests/main.test.ts
  web/tests/setup.ts
  web/vite.config.ts
  web/vitest.config.ts
Labels: feat

#12 feat: [9] 상태관리 라이브러리 redux로 변경
  web/package-lock.json
  web/src/App.tsx
  web/src/assets/logo.svg
  web/src/pages/home-page.tsx
  web/src/store/index.ts
  web/src/store/loginSlice.ts
  web/src/store/useLoginStore.ts
  web/src/types/HomePage.d.ts
Labels: docs, feat

#14 feat: [4] react-router-dom을 이용한 페이지 구조 잡기
  web/src/App.tsx
  web/src/pages/auth-page.tsx
  web/src/pages/collect-comments-page.tsx
  web/src/pages/create-survey-page.tsx
  web/src/pages/index.ts
  web/src/pages/result-page.tsx
  web/src/pages/root.tsx
Labels: feat

#17 feat: [6] react-query 초기 설정
  web/src/App.tsx
  web/src/lib/paths.ts
  web/src/lib/query-keys.ts
Labels: feat

#22 feat: [10] 공통 컴포넌트 구축
  app/assets/images/splash.png
  app/expo-env.d.ts
  web/src/App.tsx
  web/src/assets/btn_back_black.png
  web/src/assets/btn_delete.png
  web/src/assets/btn_open.png
  web/src/assets/btn_plus.png
  web/src/assets/btn_share.png
  web/src/assets/calander.png
  web/src/assets/checkRect.png
  web/src/assets/checkRound.png
  web/src/assets/comment.png
  web/src/assets/gift.png
  web/src/assets/main_card.png
  web/src/assets/retry.png
  web/src/assets/rightarrow.png
  web/src/assets/survey.png
  web/src/components/common/Btn_btns.tsx
  web/src/components/common/Btn_check.tsx
  web/src/components/common/Btn_comment.tsx
  web/src/components/common/Btn_detail.tsx
  web/src/components/common/Btn_main.tsx
  web/src/components/common/Btn_plus.tsx
  web/src/components/common/Btn_popup.tsx
  web/src/components/common/Btn_preview.tsx
  web/src/components/common/Btn_survey.tsx
  web/src/components/common/HashTag.tsx
  web/src/components/common/Popup.tsx
  web/src/components/common/SubTab.tsx
  web/src/components/common/Subtitle.tsx
  web/src/components/common/SurveyForm.tsx
  web/src/components/common/SurveyInput.tsx
  web/src/components/common/SurveyTimeInput.tsx
  web/src/components/common/Survey_Check.tsx
  web/src/components/common/main_card/MainCard.tsx
  web/src/components/common/main_card/comment.tsx
  web/src/components/common/main_card/divider.tsx
  web/src/components/common/main_card/period.tsx
  web/src/components/common/main_card/present.tsx
  web/src/components/common/main_card/tag.tsx
  web/src/components/common/main_card/title.tsx
  web/src/components/common/underLineInput.tsx
  web/src/components/myevent/CompletedContent.tsx
  web/src/components/myevent/ProgressContent.tsx
  web/src/components/myevent/Tabs.tsx
  web/src/components/myevent/index.ts
  web/src/components/ui/header.tsx
  web/src/pages/components.tsx
  web/src/pages/my-page.tsx
  web/src/pages/myevent-page.tsx
  web/src/styles/global-styles.ts
  web/src/theme.ts
Labels: feat, refactor

#24 feat: [12] 웹뷰 로그, 엡애서 출력
  app/app/_layout.tsx
  app/app/index.tsx
  app/lib/log.ts
  app/package-lock.json
  app/package.json
Labels: feat

#27 feat: [14] 댓글 수집 페이지 구현 및 기타 페이지 디자인 수정
  README.md
  web/src/App.tsx
  web/src/components/common/Btn_popup.tsx
  web/src/components/common/Popup.tsx
  web/src/components/common/Subtitle.tsx
  web/src/components/common/SurveyTimeInput.tsx
  web/src/pages/collect-comments-page.tsx
  web/src/styles/global-styles.ts
  web/src/theme.ts
Labels: feat, refactor

#29 feat: [3] webview 브릿지 구축
  app/.gitignore
  app/app.json
  app/app/index.tsx
  app/components/.gitkeep
  app/components/webview-bridge.tsx
  app/hooks/use-webview.ts
  app/lib/event-emitter.ts
  app/lib/log.ts
  app/metro.config.js
  app/package-lock.json
  app/package.json
  app/types/webview.d.ts
  web/package-lock.json
  web/package.json
  web/src/hooks/use-webview.ts
  web/src/lib/event-emitter.ts
  web/src/lib/log.ts
  web/src/main.tsx
  web/src/pages/root.tsx
  web/src/types/global.d.ts
  web/src/types/webview.d.ts
Labels: feat

#34 [FEAT] 앱 네비바, 플로팅 버튼 구현
  web/index.html
  web/package-lock.json
  web/package.json
  web/src/components/common/icons.tsx
  web/src/components/home/floating-button.styles.ts
  web/src/components/home/floating-button.tsx
  web/src/components/home/no-result.styles.ts
  web/src/components/home/no-result.tsx
  web/src/components/ui/header.tsx
  web/src/components/ui/header/header.styles.ts
  web/src/components/ui/header/index.tsx
  web/src/components/ui/overlay/index.tsx
  web/src/components/ui/overlay/overlay.styles.ts
  web/src/components/ui/tabs/index.tsx
  web/src/components/ui/tabs/tabs.styles.ts
  web/src/pages/home-page.styles.ts
  web/src/pages/home-page.tsx
  web/src/pages/my-page.tsx
  web/src/pages/myevent-page.tsx
  web/src/pages/root.styles.ts
  web/src/pages/root.tsx
  web/src/styles/global-styles.ts
Labels: feat

#36 feat: [35] 앱 - 웹뷰 연결
  app/app/_layout.tsx
  app/app/index.tsx
  web/src/components/home/no-result.styles.ts
Labels: feat

#38 feat: [15] 설문 생성 페이지 디자인 (기능x)
  web/src/App.tsx
  web/src/assets/btn_delete.png
  web/src/assets/step1.png
  web/src/assets/step2.png
  web/src/assets/step3.png
  web/src/components/Survey/ObjectiveMultipleForm.tsx
  web/src/components/Survey/ObjectiveSingleForm.tsx
  web/src/components/Survey/SubjectiveForm.tsx
  web/src/components/Survey/SurveyForm.tsx
  web/src/components/common/Btn_btns.tsx
  web/src/components/common/Btn_check.tsx
  web/src/components/common/Btn_popup.tsx
  web/src/components/common/Btn_preview.tsx
  web/src/components/common/CrawlingTime.tsx
  web/src/components/common/HashTag.tsx
  web/src/components/common/ProgressBar.tsx
  web/src/components/common/SingleDatePicker.tsx
  web/src/components/common/SubTab.tsx
  web/src/components/common/Subtitle.tsx
  web/src/components/common/SurveyInput.tsx
  web/src/components/common/SurveyTimeInput.tsx
  web/src/components/common/Survey_Check.tsx
  web/src/components/common/Tags.tsx
  web/src/components/common/TitleInput.tsx
  web/src/components/common/Winner.tsx
  web/src/components/common/underLineInput.tsx
  web/src/lib/log.ts
  web/src/pages/components.tsx
  web/src/pages/crawling-result-page.tsx
  web/src/pages/create-survey-page.tsx
  web/src/pages/create-survey-page1.tsx
  web/src/pages/create-survey-page2.tsx
  web/src/pages/create-survey-page3.tsx
  web/src/pages/index.ts
  web/src/pages/root.tsx
  web/src/store/index.ts
  web/src/store/survey/index.ts
  web/src/styles/global-styles.ts
  web/src/types/survey.d.ts
Labels: feat

#39 feat: [16] 당첨자 선정 페이지 구현
  web/src/components/common/CrawlingTime.tsx
  web/src/components/common/SurveyTimeInput.tsx
  web/src/components/common/Winner.tsx
  web/src/components/ui/tabs/tabs.styles.ts
  web/src/components/winner/Comment.tsx
  web/src/components/winner/Winner.tsx
  web/src/lib/log.ts
  web/src/pages/crawling-result-page.tsx
  web/src/store/survey/index.ts
  web/src/theme.ts
  web/src/types/survey.d.ts
Labels: feat

#41 refactor: [37] 로그인 / 회원가입 폼 리팩토링
  web/package-lock.json
  web/package.json
  web/src/components/auth/sign-in.styles.ts
  web/src/components/auth/sign-in.tsx
  web/src/components/auth/sign-up.styles.ts
  web/src/components/auth/sign-up.tsx
  web/src/components/common/Btn_btns.tsx
  web/src/components/common/form/form.styles.ts
  web/src/components/common/form/index.tsx
  web/src/components/common/header/header.styles.ts
  web/src/components/common/header/index.tsx
  web/src/components/common/input/index.tsx
  web/src/components/common/input/input.styles.ts
  web/src/components/common/label/index.tsx
  web/src/components/common/label/label.styles.ts
  web/src/components/common/overlay/index.tsx
  web/src/components/common/overlay/overlay.styles.ts
  web/src/components/common/tabs/index.tsx
  web/src/components/common/tabs/tabs.styles.ts
  web/src/components/home/floating-button.tsx
  web/src/lib/schema/auth.schema.ts
  web/src/lib/utils.ts
  web/src/main.tsx
  web/src/pages/auth-page.tsx
  web/src/pages/home-page.tsx
Labels: feat
