Repository Central-MakeUs/suppin-web, pull requests merged in 2024-08, with the labels that each got.

#43 feat: [42] react-query 설정 및 로그인 / 회원가입 api 연동
  web/package-lock.json
  web/package.json
  web/src/App.tsx
  web/src/components/auth/sign-in.tsx
  web/src/components/auth/sign-up.tsx
  web/src/lib/query-keys.ts
  web/src/lib/schema/auth.schema.ts
  web/src/pages/auth-page.tsx
  web/src/pages/crawling-result-page.tsx
  web/src/services/apis/user.service.ts
  web/src/services/axios-instance.ts
  web/src/services/queries/user.mutation.ts
  web/src/services/queries/user.queries.ts
  web/src/types/user.ts
  web/vite.config.ts
Labels: feat

#45 feat: [44] 메인페이지 완료
  web/src/assets/no-result.svg
  web/src/components/common/BtnComment.tsx
  web/src/components/common/BtnSurvey.tsx
  web/src/components/common/Btn_plus.tsx
  web/src/components/common/Btn_preview.tsx
  web/src/components/common/box/box.styles.ts
  web/src/components/common/box/index.tsx
  web/src/components/home/floating-button.styles.ts
  web/src/components/home/floating-button.tsx
  web/src/components/home/floating-menu.styles.ts
  web/src/components/home/floating-menu.tsx
  web/src/components/home/no-result.styles.ts
  web/src/components/home/no-result.tsx
  web/src/styles/global-styles.ts
Labels: feat

#48 feat: [47] router lazy 로드 추가
  web/src/App.tsx
  web/src/pages/collect-comments-page.tsx
  web/src/pages/crawling-result-page.tsx
  web/src/pages/create-survey-page.tsx
  web/src/pages/index.ts
  web/src/pages/myevent-page.tsx
  web/src/pages/result-page.tsx
Labels: refactor

#52 refactor: [51] 회원가입 수정 및 기타 페이지 수정 중
  web/src/App.tsx
  web/src/assets/btn_mypage.png
  web/src/assets/calander1.png
  web/src/assets/rigth.png
  web/src/assets/uncheckRound.png
  web/src/components/auth/sign-up.styles.ts
  web/src/components/auth/sign-up.tsx
  web/src/components/auth/sign-up1.tsx
  web/src/components/auth/sign-up2.tsx
  web/src/components/auth/sign-up3.tsx
  web/src/components/common/CrawlingTime.tsx
  web/src/components/common/Subtitle.tsx
  web/src/components/common/Tags.tsx
  web/src/components/common/Winner.tsx
  web/src/components/common/input/input.styles.ts
  web/src/components/winner/Comment.tsx
  web/src/components/winner/Winner.tsx
  web/src/lib/schema/auth.schema.ts
  web/src/pages/auth-page.tsx
  web/src/pages/crawling-result-page.tsx
  web/src/pages/create-survey-page.tsx
  web/src/pages/create-survey-page2.tsx
  web/src/pages/create-survey-page3.tsx
  web/src/pages/my-page.tsx
  web/src/pages/survey-preview-page.tsx
  web/src/services/apis/user.service.ts
  web/src/services/queries/user.mutation.ts
  web/src/store/index.ts
  web/src/store/signup/signup/index.ts
  web/src/store/signup/terms/index.ts
  web/src/store/survey/index.ts
  web/src/store/winner/index.ts
  web/src/types/signup/email.d.ts
  web/src/types/signup/signup.d.ts
  web/src/types/signup/temrs.d.ts
  web/src/types/survey.d.ts
  web/src/types/winner.d.ts
Labels: feat, refactor

#54 feat: [53] 아이디 중복 확인 구현
  web/src/components/auth/sign-up2.tsx
  web/src/components/auth/sign-up3.tsx
  web/src/components/common/Subtitle.tsx
  web/src/components/common/form/form.styles.ts
Labels: feat

#56 feat: [55] 마이페이지, 회원탈퇴 구현
  web/package-lock.json
  web/package.json
  web/src/App.tsx
  web/src/assets/step1.png
  web/src/assets/step2.png
  web/src/assets/step3.png
  web/src/components/auth/sign-in.tsx
  web/src/components/auth/sign-up1.tsx
  web/src/components/auth/sign-up2.tsx
  web/src/components/common/header/header.styles.ts
  web/src/components/common/header/index.tsx
  web/src/components/mypage/DeleteModal.tsx
  web/src/components/mypage/user-info.styles.ts
  web/src/components/mypage/user-info.tsx
  web/src/lib/query-keys.ts
  web/src/lib/schema/auth.schema.ts
  web/src/pages/my-page.tsx
  web/src/services/apis/user.service.ts
  web/src/services/axios-instance.ts
  web/src/services/queries/user.mutation.ts
  web/src/services/queries/user.queries.ts
  web/src/types/user.ts
Labels: feat

#60 feat: [58] 전체 이벤트 조회 및 비밀번호 변경, 회원가입 유형 추가
  web/package-lock.json
  web/package.json
  web/src/assets/chain.png
  web/src/assets/main_card2.png
  web/src/assets/no-result.svg
  web/src/assets/step1.png
  web/src/assets/step2.png
  web/src/assets/step3.png
  web/src/components/auth/change-pwd.tsx
  web/src/components/auth/sign-up3.tsx
  web/src/components/common/SingleDatePicker.tsx
  web/src/components/common/Tags.tsx
  web/src/components/common/box/box.styles.ts
  web/src/components/home/event-list.tsx
  web/src/components/home/no-result.styles.ts
  web/src/lib/schema/auth.schema.ts
  web/src/pages/collect-comments-page.tsx
  web/src/pages/create-survey-page2.tsx
  web/src/pages/home-page.tsx
  web/src/pages/my-page.tsx
  web/src/services/apis/user.service.ts
  web/src/services/queries/user.mutation.ts
  web/src/styles/slide.css
Labels: feat

#62 Feature: [59] 설문 생성하기 api 연동
  web/package-lock.json
  web/package.json
  web/src/components/Survey/SurveyForm.tsx
  web/src/components/Survey/create-survey-page.styles.ts
  web/src/components/Survey/create-survey-page1.tsx
  web/src/components/Survey/create-survey-page2.tsx
  web/src/components/Survey/create-survey-page3.tsx
  web/src/components/auth/change-pwd.tsx
  web/src/components/common/SingleDatePicker.tsx
  web/src/components/common/SurveyTimeInput.tsx
  web/src/components/common/box/box.styles.ts
  web/src/components/common/date-picker/single-date-picker.styles.ts
  web/src/components/common/date-picker/single-date-picker.tsx
  web/src/components/common/preview-button.tsx
  web/src/components/common/textarea/index.tsx
  web/src/components/common/textarea/textarea.styles.ts
  web/src/components/home/event-list.tsx
  web/src/components/home/floating-menu.tsx
  web/src/components/winner/Winner.tsx
  web/src/lib/query-keys.ts
  web/src/lib/schema/event.schema.ts
  web/src/pages/collect-comments-page.tsx
  web/src/pages/create-survey-page.tsx
  web/src/pages/create-survey-page1.tsx
  web/src/pages/home-page.tsx
  web/src/pages/root.tsx
  web/src/services/apis/event.service.ts
  web/src/services/apis/survey.service.ts
  web/src/services/apis/user.service.ts
  web/src/services/queries/event.mutation.ts
  web/src/services/queries/event.queries.ts
  web/src/store/comment/index.ts
  web/src/types/comment.ts
  web/src/types/event.ts
  web/src/types/survey.ts
Labels: feat

#64 feat: [63] 로딩 상태 추가 / 자잘한 버그 수정
  web/src/components/Survey/create-survey-page1.tsx
  web/src/components/auth/sign-up1.tsx
  web/src/components/auth/sign-up2.tsx
  web/src/components/common/date-picker/single-date-picker.tsx
  web/src/components/common/loader/index.tsx
  web/src/components/common/loader/loader.styles.ts
  web/src/components/home/event-list.tsx
  web/src/pages/home-page.tsx
  web/src/services/queries/user.mutation.ts
  web/src/types/event.ts
Labels: feat

#67 Feature/66 설문 생성 페이지 완료
  web/package-lock.json
  web/package.json
  web/src/assets/cancel.svg
  web/src/components/Survey/choice.styles.ts
  web/src/components/Survey/choice.tsx
  web/src/components/Survey/create-survey-page1.styles.ts
  web/src/components/Survey/create-survey-page1.tsx
  web/src/components/Survey/create-survey-page2.styles.ts
  web/src/components/Survey/create-survey-page2.tsx
  web/src/components/Survey/create-survey-page3.styles.ts
  web/src/components/Survey/create-survey-page3.tsx
  web/src/components/Survey/question-select.styles.ts
  web/src/components/Survey/question-select.tsx
  web/src/components/Survey/subjective.styles.ts
  web/src/components/Survey/subjective.tsx
  web/src/components/common/badge/badge.styles.ts
  web/src/components/common/badge/index.tsx
  web/src/components/common/select/index.tsx
  web/src/components/common/select/select.styles.ts
  web/src/pages/create-survey-page.tsx
  web/src/pages/root.tsx
  web/src/services/queries/event.mutation.ts
  web/src/services/queries/survey.mutation.ts
  web/src/store/survey/index.ts
  web/src/types/survey.ts
Labels: feat

#65 feat: [61] 댓글 수집, 크롤링, 당첨자 선정 구현
  web/package-lock.json
  web/package.json
  web/src/App.tsx
  web/src/assets/commentComplete.png
  web/src/assets/main_card_big.png
  web/src/assets/main_card_big2.png
  web/src/components/auth/sign-up.styles.ts
  web/src/components/auth/sign-up1.tsx
  web/src/components/auth/sign-up2.tsx
  web/src/components/auth/sign-up3.tsx
  web/src/components/auth/timer.tsx
  web/src/components/common/Ask_Popup.tsx
  web/src/components/common/CrawlingTime.tsx
  web/src/components/common/Popup.tsx
  web/src/components/common/SingleDatePicker.tsx
  web/src/components/common/Subtitle.tsx
  web/src/components/common/SurveyTimeInput.tsx
  web/src/components/common/Tags.tsx
  web/src/components/common/Winner.tsx
  web/src/components/common/loader/loader.styles.ts
  web/src/components/home/event-list.tsx
  web/src/components/myevent/CompletedContent.tsx
  web/src/components/myevent/DoneEventCard.tsx
  web/src/components/myevent/ProcessingEventCard.tsx
  web/src/components/myevent/ProgressContent.tsx
  web/src/components/mypage/change-pwd.tsx
  web/src/components/mypage/terms.tsx
  web/src/components/winner/Comment.tsx
  web/src/components/winner/Winner.tsx
  web/src/components/winner/WinnerResult.tsx
  web/src/lib/timeUtil.ts
  web/src/main.tsx
  web/src/pages/collect-comments-page.tsx
  web/src/pages/crawling-result-page.tsx
  web/src/pages/home-page.tsx
  web/src/pages/my-page.tsx
  web/src/services/apis/crawling.service.ts
  web/src/services/apis/user.service.ts
  web/src/services/queries/user.mutation.ts
  web/src/store/collect/index.ts
  web/src/store/comment/index.ts
  web/src/store/crawling/index.ts
  web/src/store/index.ts
  web/src/store/winner/index.ts
  web/src/types/comment.d.ts
  web/src/types/signup/collect.ts
  web/src/types/signup/crawling.ts
  web/src/types/winner.d.ts
Labels: feat

#77 refactor: 개인정보 수집 버그 수정
  web/src/components/Survey/create-survey-page2.styles.ts
  web/src/components/Survey/create-survey-page2.tsx
Labels: refactor

#76 feature/69 설문 미리보기 기능 추가
  web/package-lock.json
  web/package.json
  web/src/components/Survey/create-survey-page1.tsx
  web/src/components/Survey/create-survey-page2.tsx
  web/src/components/Survey/create-survey-page3.tsx
  web/src/components/Survey/preview/choice.styles.ts
  web/src/components/Survey/preview/choice.tsx
  web/src/components/Survey/preview/event-intro.styles.ts
  web/src/components/Survey/preview/event-intro.tsx
  web/src/components/Survey/preview/personal.styles.ts
  web/src/components/Survey/preview/personal.tsx
  web/src/components/Survey/preview/policy.styles.ts
  web/src/components/Survey/preview/policy.tsx
  web/src/components/Survey/preview/subjective.styles.ts
  web/src/components/Survey/preview/subjective.tsx
  web/src/components/Survey/preview/survey-preview.styles.ts
  web/src/components/Survey/preview/survey-preview.tsx
  web/src/components/common/preview-button.tsx
  web/src/components/winner/result-content.tsx
  web/src/pages/create-survey-page.tsx
  web/src/services/queries/event.mutation.ts
  web/src/store/survey/index.ts
  web/src/types/survey.ts
Labels: feat

#78 refactor: 설문 질문 생성 버그 수정
  web/src/components/Survey/choice.tsx
  web/src/components/Survey/create-survey-page3.tsx
  web/src/components/Survey/question-select.tsx
Labels: refactor

#79 refactor: [70] 폼 에러 메시지 디자인 수정
  web/src/components/Survey/create-survey-page1.styles.ts
  web/src/components/Survey/create-survey-page1.tsx
  web/src/components/auth/sign-up1.tsx
  web/src/components/common/form/form.styles.ts
Labels: refactor

#81 feature: [80] 당첨자 선정 로직 수정
  web/src/components/winner/survey-winner.styles.ts
  web/src/components/winner/survey-winner.tsx
  web/src/lib/schema/winner.schema.ts
  web/src/types/winner.d.ts
Labels: feat

#75 refactor: [74] 날짜 선택 범위 수정, 8/25 QA 반영
  app/app.json
  app/eas.json
  web/package-lock.json
  web/src/assets/icon.png
  web/src/components/common/SingleDatePicker.tsx
  web/src/components/common/Subtitle.tsx
  web/src/components/common/SurveyTimeInput.tsx
  web/src/components/myevent/DoneEventCard.tsx
  web/src/components/myevent/ProcessingEventCard.tsx
  web/src/lib/timeUtil.ts
  web/src/pages/crawling-result-page.tsx
  web/src/pages/home-page.tsx
  web/src/store/winner/index.ts
Labels: refactor
